return {
    author = "zarg4n",
    version = "0.2.0",
    target_title_update = "TU1.6.4",
    state_file_prefix = "zarg4n_career_",
    min_supported_age = 14,
    max_profile_age = 35,
    max_dynamic_potential_age = 29,
    max_potential_delta_per_season = 3,
    min_potential_delta_per_season = -2,
    sample_confidence_floor = 0.15,
    regular_appearance_sample = 10,
    max_height_delta_cm = 7,
    max_weight_delta_kg = 8,
    debug = true,
}
